apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-app
  labels:
    app: three-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-app
  template:
    metadata:
      labels:
        app: three-tier-app
    spec:
      containers:
        - name: three-tier-app
          image: shubhamsaxena2207/flask-app:latest
          env:
            - name: MYSQL_HOST
              value: "mysql.default.svc.cluster.local"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: db_password
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_DB
              value: "my_db"
          ports:
            - containerPort: 9000
          imagePullPolicy: Always
