apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-app
  labels:
    app: three-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-app
  template:
    metadata:
      labels:
        app: three-tier-app
    spec:
      containers:
        - name: three-tier-app
          image: shubhamsaxena2207/flask-app:latest
          env:
            - name: MYSQL_HOST
              value: "10.98.19.211"          # this is your mysql's service clusture IP, Make sure to change it with yours
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 9000
          imagePullPolicy: Always
